//
//  FakeUIKit.h
//  FakeUIKit
//
//  Created by Eric Chamberlain on 4/22/15.
//  Copyright (c) 2015 Upstart Illustration LLC. All rights reserved.
//

#import <Foundation/Foundation.h>

//#import <FakeUIKit/UIKit.h>

//! Project version number for FakeUIKit.
FOUNDATION_EXPORT double FakeUIKitVersionNumber;

//! Project version string for FakeUIKit.
FOUNDATION_EXPORT const unsigned char FakeUIKitVersionString[];

#import <FakeUIKit/UIKitDefines.h>
#import <FakeUIKit/UIAccelerometer.h>
#import <FakeUIKit/UIAccessibility.h>
#import <FakeUIKit/UIActivityIndicatorView.h>
#import <FakeUIKit/UIActivity.h>
#import <FakeUIKit/UIActivityItemProvider.h>
#import <FakeUIKit/UIActivityViewController.h>
#import <FakeUIKit/UIActionSheet.h>
#import <FakeUIKit/UIAlertController.h>
#import <FakeUIKit/UIAlertView.h>
#import <FakeUIKit/UIAppearance.h>
#import <FakeUIKit/UIApplication.h>
#import <FakeUIKit/UIBarButtonItem.h>
#import <FakeUIKit/UIBarItem.h>
#import <FakeUIKit/UIBezierPath.h>
#import <FakeUIKit/UIButton.h>
#import <FakeUIKit/UICollectionView.h>
#import <FakeUIKit/UICollectionViewCell.h>
#import <FakeUIKit/UICollectionViewController.h>
#import <FakeUIKit/UICollectionViewFlowLayout.h>
#import <FakeUIKit/UICollectionViewLayout.h>
#import <FakeUIKit/UICollectionViewTransitionLayout.h>
#import <FakeUIKit/UIColor.h>
#import <FakeUIKit/UIControl.h>
#import <FakeUIKit/UIDataDetectors.h>
#import <FakeUIKit/UIDatePicker.h>
#import <FakeUIKit/UIDevice.h>
#import <FakeUIKit/UIDocument.h>
#import <FakeUIKit/UIDocumentInteractionController.h>
#import <FakeUIKit/UIDocumentPickerViewController.h>
#import <FakeUIKit/UIDocumentMenuViewController.h>
#import <FakeUIKit/UIDocumentPickerExtensionViewController.h>
#import <FakeUIKit/NSFileProviderExtension.h>
#import <FakeUIKit/UIVisualEffectView.h>
#import <FakeUIKit/UIEvent.h>
#import <FakeUIKit/UIFont.h>
#import <FakeUIKit/UIFontDescriptor.h>
#import <FakeUIKit/UIGeometry.h>
#import <FakeUIKit/UIGestureRecognizer.h>
#import <FakeUIKit/UIGraphics.h>
#import <FakeUIKit/UIImage.h>
#import <FakeUIKit/UIImageAsset.h>
#import <FakeUIKit/UIImagePickerController.h>
#import <FakeUIKit/UIImageView.h>
#import <FakeUIKit/UIInputView.h>
#import <FakeUIKit/UIInputViewController.h>
#import <FakeUIKit/UIInterface.h>
#import <FakeUIKit/UILabel.h>
#import <FakeUIKit/UILexicon.h>
#import <FakeUIKit/UILocalNotification.h>
#import <FakeUIKit/UIUserNotificationSettings.h>
#import <FakeUIKit/UILocalizedIndexedCollation.h>
#import <FakeUIKit/UILongPressGestureRecognizer.h>
#import <FakeUIKit/UIManagedDocument.h>
#import <FakeUIKit/UIMenuController.h>
#import <FakeUIKit/UIMotionEffect.h>
#import <FakeUIKit/UINavigationBar.h>
#import <FakeUIKit/UINavigationController.h>
#import <FakeUIKit/UINib.h>
#import <FakeUIKit/UINibDeclarations.h>
#import <FakeUIKit/UINibLoading.h>
#import <FakeUIKit/UIPageControl.h>
#import <FakeUIKit/UIPageViewController.h>
#import <FakeUIKit/UIPanGestureRecognizer.h>
#import <FakeUIKit/UIPasteboard.h>
#import <FakeUIKit/UIPickerView.h>
#import <FakeUIKit/UIPinchGestureRecognizer.h>
#import <FakeUIKit/UIPopoverController.h>
#import <FakeUIKit/UIPopoverBackgroundView.h>
#import <FakeUIKit/UIPrinter.h>
#import <FakeUIKit/UIPrinterPickerController.h>
#import <FakeUIKit/UIPrintError.h>
#import <FakeUIKit/UIPrintFormatter.h>
#import <FakeUIKit/UIPrintInfo.h>
#import <FakeUIKit/UIPrintInteractionController.h>
#import <FakeUIKit/UIPrintPageRenderer.h>
#import <FakeUIKit/UIPrintPaper.h>
#import <FakeUIKit/UIProgressView.h>
#import <FakeUIKit/UIReferenceLibraryViewController.h>
#import <FakeUIKit/UIRefreshControl.h>
#import <FakeUIKit/UIResponder.h>
#import <FakeUIKit/UIRotationGestureRecognizer.h>
#import <FakeUIKit/UIScreen.h>
#import <FakeUIKit/UIScreenEdgePanGestureRecognizer.h>
#import <FakeUIKit/UIScreenMode.h>
#import <FakeUIKit/UIScrollView.h>
#import <FakeUIKit/UISearchBar.h>
#import <FakeUIKit/UISearchController.h>
#import <FakeUIKit/UISearchDisplayController.h>
#import <FakeUIKit/UISegmentedControl.h>
#import <FakeUIKit/UISlider.h>
#import <FakeUIKit/UISplitViewController.h>
#import <FakeUIKit/UIStepper.h>
#import <FakeUIKit/UIStoryboard.h>
#import <FakeUIKit/UIStoryboardPopoverSegue.h>
#import <FakeUIKit/UIStoryboardSegue.h>
#import <FakeUIKit/UIStringDrawing.h>
#import <FakeUIKit/UISwipeGestureRecognizer.h>
#import <FakeUIKit/UISwitch.h>
#import <FakeUIKit/UITabBar.h>
#import <FakeUIKit/UITabBarController.h>
#import <FakeUIKit/UITabBarItem.h>
#import <FakeUIKit/UITableView.h>
#import <FakeUIKit/UITableViewHeaderFooterView.h>
#import <FakeUIKit/UITableViewCell.h>
#import <FakeUIKit/UITableViewController.h>
#import <FakeUIKit/UITapGestureRecognizer.h>
#import <FakeUIKit/UITextChecker.h>
#import <FakeUIKit/UITextField.h>
#import <FakeUIKit/UITextInput.h>
#import <FakeUIKit/UITextInputTraits.h>
#import <FakeUIKit/UITextView.h>
#import <FakeUIKit/UIToolbar.h>
#import <FakeUIKit/UITouch.h>
#import <FakeUIKit/UITraitCollection.h>
#import <FakeUIKit/UIVideoEditorController.h>
#import <FakeUIKit/UIView.h>
#import <FakeUIKit/UIViewController.h>
#import <FakeUIKit/UIWebView.h>
#import <FakeUIKit/UIWindow.h>
#import <FakeUIKit/NSAttributedString.h>
#import <FakeUIKit/NSLayoutConstraint.h>
#import <FakeUIKit/NSLayoutManager.h>
#import <FakeUIKit/NSParagraphStyle.h>
#import <FakeUIKit/NSShadow.h>
#import <FakeUIKit/NSStringDrawing.h>
#import <FakeUIKit/NSText.h>
#import <FakeUIKit/NSTextAttachment.h>
#import <FakeUIKit/NSTextContainer.h>
#import <FakeUIKit/NSTextStorage.h>
#import <FakeUIKit/UIStateRestoration.h>
#import <FakeUIKit/UIViewControllerTransitioning.h>
#import <FakeUIKit/UIViewControllerTransitionCoordinator.h>
#import <FakeUIKit/UIPresentationController.h>
#import <FakeUIKit/UIPopoverPresentationController.h>
#import <FakeUIKit/UIDynamicAnimator.h>
#import <FakeUIKit/UIDynamicBehavior.h>
#import <FakeUIKit/UIPushBehavior.h>
#import <FakeUIKit/UISnapBehavior.h>
#import <FakeUIKit/UIDynamicItemBehavior.h>
#import <FakeUIKit/UIGravityBehavior.h>
#import <FakeUIKit/UIAttachmentBehavior.h>
#import <FakeUIKit/UICollisionBehavior.h>
